// _demo/vuecli3-ts-startkit-justable-demo/src/components/Header.vue
<template>
  <header class="header">
    <div class="header-left">
      <h2 class="title animated slower infinite rubberBandDelay">{{name}}</h2>
    </div>
    <div class="header-right">
      <router-link to="/">登出</router-link>
    </div>
  </header>
</template>
<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator'

@Component
export default class Header extends Vue {
  @Prop(String) name!: String
  handleSelect (key: string, keyPath: string) {
    console.log(key, keyPath)
  }
}
// @Prop(Number) name!: number
// @Prop({ default: 'default value' }) name!: string
// @Prop([String, Boolean]) name!: string | boolean
</script>

// _demo/cra-react-ts-startkit-justable-demo/src/components/Home/Header.tsx
import * as React from "react"

const Header = ({ userName, history }: any) => {
  const onClick = () => {
    history.push('/')
  }
  return (
    <header className="header">
      <div className="header-left">
        <h2 className="title animated slower infinite rubberBandDelay">{ userName }</h2>
      </div>
      <div className="header-right">
        <a className="router-link-active" href="javascript:void(0)" onClick={onClick}>登出</a>
      </div>
    </header>
  )
}
  

export default Header
